name: Checks
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - run: sudo apt-get update && sudo apt-get install --no-install-recommends -y shellcheck
      - run: ./scripts/lint.sh
      - run: ./scripts/test.sh --source
